version: 0.0
os: linux
files:
  - source: dist/my-angular-project/
    destination: /var/www/html/my-angular-project
permissions:
- object: /var/www/html/my-angular-project
  pattern: '**'
  mode: '0755'
  owner: root
  group: root
  type: 
    - files
    - directory
hooks: 
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 300